Repository MasoniteFramework/masonite, pull requests merged in 2022-04, with the labels that each got.

#522 Add new version of `exceptionite` to improve debugging experience
  requirements.txt
  setup.py
  src/masonite/configuration/Configuration.py
  src/masonite/exceptions/ExceptionHandler.py
  src/masonite/exceptions/JsonHandler.py
  src/masonite/exceptions/__init__.py
  src/masonite/exceptions/exceptionite/__init__.py
  src/masonite/exceptions/exceptionite/blocks.py
  src/masonite/exceptions/exceptionite/controllers.py
  src/masonite/exceptions/exceptionite/solutions.py
  src/masonite/exceptions/exceptionite/tabs.py
  src/masonite/exceptions/handlers/DumpExceptionHandler.py
  src/masonite/exceptions/handlers/HttpExceptionHandler.py
  src/masonite/middleware/route/VerifyCsrfToken.py
  src/masonite/providers/ExceptionProvider.py
  tests/features/dumps/test_dump_exception_handler.py
  tests/integrations/config/exceptions.py
Labels: enhancement

#580 Fix `optional` helper
  src/masonite/helpers/optional.py
  tests/core/helpers/test_optional.py
Labels: Next Patch

#576 Add more config options to AMQP driver
  src/masonite/drivers/queue/AMQPDriver.py
  tests/integrations/config/queue.py
Labels: Next Patch

#575 Add ability to pass query parameters to `url` and `route` helpers and to `redirect` method
  src/masonite/helpers/urls.py
  src/masonite/response/response.py
  src/masonite/routes/HTTPRoute.py
  src/masonite/routes/Router.py
  src/masonite/utils/str.py
  tests/core/helpers/test_urls.py
  tests/core/response/test_response_redirections.py
  tests/routes/test_routes.py
Labels: Next Minor

#526 Add type hinting to codebase
  src/masonite/authorization/AuthorizesRequest.py
  src/masonite/broadcasting/Broadcast.py
  src/masonite/cache/Cache.py
  src/masonite/commands/CommandCapsule.py
  src/masonite/drivers/queue/DatabaseDriver.py
  src/masonite/drivers/session/CookieDriver.py
  src/masonite/facades/Auth.pyi
  src/masonite/facades/Config.pyi
  src/masonite/facades/Dump.pyi
  src/masonite/facades/Gate.pyi
  src/masonite/facades/Hash.pyi
  src/masonite/facades/Loader.pyi
  src/masonite/facades/Mail.pyi
  src/masonite/facades/Notification.pyi
  src/masonite/facades/Queue.pyi
  src/masonite/facades/Request.pyi
  src/masonite/facades/Response.pyi
  src/masonite/facades/Session.pyi
  src/masonite/facades/Storage.pyi
  src/masonite/facades/Url.pyi
  src/masonite/facades/View.pyi
  src/masonite/filesystem/Storage.py
  src/masonite/foundation/Application.py
  src/masonite/foundation/Kernel.py
  src/masonite/foundation/response_handler.py
  src/masonite/headers/Header.py
  src/masonite/headers/HeaderBag.py
  src/masonite/helpers/urls.py
  src/masonite/providers/Provider.py
  src/masonite/request/request.py
  src/masonite/request/validation.py
  src/masonite/response/response.py
  src/masonite/sessions/Session.py
  src/masonite/sessions/helpers.py
  src/masonite/tests/HttpTestResponse.py
  src/masonite/tests/TestCase.py
  src/masonite/tests/TestCommand.py
  src/masonite/views/view.py
  tests/features/validation/test_validation.py
  tests/integrations/config/mail.py
Labels: refactoring

#581 Fix setting session when middleware redirects instead of continuing request flow
  src/masonite/middleware/route/SessionMiddleware.py
  src/masonite/sessions/Session.py
  tests/features/session/test_cookie_session.py
  tests/features/session/test_requests.py
Labels: Next Patch

#587 Fixed `dd` and `dump` helpers which were not dumping into console
  src/masonite/dumps/Dump.py
  src/masonite/dumps/Dumper.py
  tests/features/dumps/test_dump_exception_handler.py
  tests/features/dumps/test_dumper.py
Labels: Next Patch

#595 Bump `cryptography` dependency version and use their new version scheme
  setup.py
Labels: Next Patch

#509 Handle `ModelNotFound` exceptions as HTTP 404 errors
  src/masonite/exceptions/__init__.py
  src/masonite/exceptions/exceptions.py
  src/masonite/exceptions/handlers/ModelNotFoundHandler.py
  src/masonite/providers/ExceptionProvider.py
  tests/core/request/test_http_requests.py
  tests/integrations/controllers/WelcomeController.py
  tests/integrations/web.py
Labels: enhancement, Next Minor

#594 Fixed getting extension such as `.tar.gz` from files in filesystem feature
  src/masonite/filesystem/File.py
  src/masonite/filesystem/FileStream.py
  src/masonite/filesystem/UploadedFile.py
  src/masonite/filesystem/drivers/AmazonS3Driver.py
  src/masonite/filesystem/drivers/LocalDriver.py
  src/masonite/utils/filesystem.py
  tests/core/utils/test_filesystem.py
  tests/features/storage/test_local_storage.py
Labels: Next Patch

#598 Add ability to resolve simple instance as controller in routes
  src/masonite/exceptions/exceptionite/blocks.py
  src/masonite/routes/HTTPRoute.py
  src/masonite/routes/commands/RouteListCommand.py
  src/masonite/utils/str.py
  tests/core/utils/test_str.py
  tests/integrations/controllers/WelcomeController.py
  tests/routes/test_parsing_controllers.py
Labels: Next Minor

#599 Added `stop` and `dump` features to TestCase
  src/masonite/tests/HttpTestResponse.py
  src/masonite/tests/TestCase.py
  tests/tests/test_testcase.py
Labels: Next Minor

#602 Add `http_method` view helper to change request method in HTML forms
  src/masonite/providers/HelpersProvider.py
  src/masonite/request/request.py
  src/masonite/tests/TestCase.py
  tests/core/request/test_request.py
  tests/core/views/test_view.py
  tests/integrations/templates/test_helpers.html
Labels: Next Minor

#604 Fix order of published package migrations
  src/masonite/packages/providers/PackageProvider.py
  src/masonite/tests/TestCase.py
  tests/features/packages/test_publish.py
  tests/integrations/test_package/migrations/create_other_table.py
  tests/integrations/test_package/providers/MyTestPackageProvider.py
Labels: Next Patch

#596 Add database validation rules `exists_in_db` and `unique_in_db`
  src/masonite/validation/Validator.py
  src/masonite/validation/__init__.py
  tests/features/validation/test_validation.py
Labels: Next Minor

#553 Added feature to share individual input validation errors in session
  src/masonite/middleware/__init__.py
  src/masonite/middleware/route/ShareErrorsInSessionMiddleware.py
  src/masonite/tests/HttpTestResponse.py
  src/masonite/views/view.py
  tests/integrations/app/Kernel/Kernel.py
  tests/integrations/controllers/WelcomeController.py
  tests/integrations/templates/contact.html
  tests/integrations/web.py
Labels: enhancement, Next Minor
